/** @type {{ name: string; category: string; tags: string[]; price: number; manufacturer: string; }[]} */
export const products = [
    {
        name: 'AMD Ryzen 5 8600G 6 Cores',
        category: 'CPU',
        tags: ['6 Cores', '4.3 GHz', 'AM5', 'Integrated Graphics'],
        price: 3_100_000,
        manufacturer: 'AMD',
    },
    {
        name: 'Intel Core i3-12100 4 Cores',
        category: 'CPU',
        tags: ['4 Cores', '3.3 GHz', 'LGA1700'],
        price: 1_550_000,
        manufacturer: 'Intel',
    },
    {
        name: 'AMD Ryzen 5 9600X 6 Cores',
        category: 'CPU',
        tags: ['6 Cores', '4.7 GHz', 'AM5'],
        price: 4_650_000,
        manufacturer: 'AMD',
    },
    {
        name: 'Intel Core i5-14600K 14 Cores',
        category: 'CPU',
        tags: ['14 Cores', '5.3 GHz', 'LGA1700'],
        price: 6_200_000,
        manufacturer: 'Intel',
    },
    {
        name: 'Intel Core Ultra 9 285K 24 Cores',
        category: 'CPU',
        tags: ['24 Cores', '5.7 GHz', 'LGA1851'],
        price: 12_400_000,
        manufacturer: 'Intel',
    },
    {
        name: 'AMD Ryzen 9 9950X 16 Cores',
        category: 'CPU',
        tags: ['16 Cores', '5.7 GHz', 'AM5'],
        price: 9_300_000,
        manufacturer: 'AMD',
    },
    {
        name: 'MSI MAG COREFROZR AA13 ARGB',
        category: 'CPU Cooler',
        tags: ['Air Cooler', 'ARGB'],
        price: 320_000,
        manufacturer: 'MSI',
    },
    {
        name: 'darkFlash Darkair Pro 120mm',
        category: 'CPU Cooler',
        tags: ['Air Cooler', '120mm Fan'],
        price: 345_000,
        manufacturer: 'darkFlash',
    },
    {
        name: 'Thermalright Peerless Assassin 120',
        category: 'CPU Cooler',
        tags: ['Dual Tower', 'Air Cooler'],
        price: 620_000,
        manufacturer: 'Thermalright',
    },
    {
        name: 'Noctua NH-U12S',
        category: 'CPU Cooler',
        tags: ['Single Tower', 'Air Cooler'],
        price: 1_240_000,
        manufacturer: 'Noctua',
    },
    {
        name: 'Noctua NH-D15 G2',
        category: 'CPU Cooler',
        tags: ['Dual Tower', 'Air Cooler'],
        price: 2_325_000,
        manufacturer: 'Noctua',
    },
    {
        name: 'Corsair iCUE H150i Elite Capellix 360mm',
        category: 'CPU Cooler',
        tags: ['AIO Liquid', '360mm Radiator'],
        price: 3_875_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'ASRock B550M-HDV',
        category: 'Motherboard',
        tags: ['Micro-ATX', 'AM4'],
        price: 1_150_000,
        manufacturer: 'ASRock',
    },
    {
        name: 'Gigabyte B650 AORUS Elite AX',
        category: 'Motherboard',
        tags: ['ATX', 'AM5'],
        price: 2_325_000,
        manufacturer: 'Gigabyte',
    },
    {
        name: 'ASUS Prime B550M-A',
        category: 'Motherboard',
        tags: ['Micro-ATX', 'AM4'],
        price: 1_860_000,
        manufacturer: 'ASUS',
    },
    {
        name: 'MSI MAG B650 Tomahawk WiFi',
        category: 'Motherboard',
        tags: ['ATX', 'AM5'],
        price: 3_100_000,
        manufacturer: 'MSI',
    },
    {
        name: 'ASUS ROG Crosshair X870E Extreme',
        category: 'Motherboard',
        tags: ['E-ATX', 'AM5'],
        price: 15_484_500,
        manufacturer: 'ASUS',
    },
    {
        name: 'MSI MPG Z890 Carbon WiFi',
        category: 'Motherboard',
        tags: ['ATX', 'LGA1851'],
        price: 6_200_000,
        manufacturer: 'MSI',
    },
    {
        name: 'MSI MAG A550BN 550W',
        category: 'Power Supply Unit',
        tags: ['550W', '80+ Bronze'],
        price: 775_000,
        manufacturer: 'MSI',
    },
    {
        name: 'Cooler Master MWE 550 V2 Bronze',
        category: 'Power Supply Unit',
        tags: ['550W', '80+ Bronze'],
        price: 930_000,
        manufacturer: 'Cooler Master',
    },
    {
        name: 'be quiet! Straight Power 12 750W',
        category: 'Power Supply Unit',
        tags: ['750W', '80+ Gold'],
        price: 1_860_000,
        manufacturer: 'be quiet!',
    },
    {
        name: 'Corsair RM750x 750W',
        category: 'Power Supply Unit',
        tags: ['750W', '80+ Gold'],
        price: 1_705_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'be quiet! Dark Power 13 1000W',
        category: 'Power Supply Unit',
        tags: ['1000W', '80+ Titanium'],
        price: 3_100_000,
        manufacturer: 'be quiet!',
    },
    {
        name: 'Seasonic Prime TX-1000 Titanium',
        category: 'Power Supply Unit',
        tags: ['1000W', '80+ Titanium'],
        price: 4_650_000,
        manufacturer: 'Seasonic',
    },
    {
        name: 'Antec NX100 Mid Tower',
        category: 'Case',
        tags: ['Mid Tower', 'ATX'],
        price: 775_000,
        manufacturer: 'Antec',
    },
    {
        name: 'Phanteks Eclipse P300A',
        category: 'Case',
        tags: ['Mid Tower', 'ATX'],
        price: 930_000,
        manufacturer: 'Phanteks',
    },
    {
        name: 'Corsair 4000D Airflow',
        category: 'Case',
        tags: ['Mid Tower', 'ATX'],
        price: 1_550_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'Fractal Design Meshify 2',
        category: 'Case',
        tags: ['Mid Tower', 'ATX'],
        price: 2_170_000,
        manufacturer: 'Fractal Design',
    },
    {
        name: 'Lian Li O11 Dynamic EVO',
        category: 'Case',
        tags: ['Mid Tower', 'E-ATX'],
        price: 2_325_000,
        manufacturer: 'Lian Li',
    },
    {
        name: 'Corsair 5000D Airflow',
        category: 'Case',
        tags: ['Full Tower', 'E-ATX'],
        price: 2_480_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'NVIDIA GeForce RTX 4060 8GB',
        category: 'GPU',
        tags: ['8GB GDDR6', 'RTX'],
        price: 4_650_000,
        manufacturer: 'NVIDIA',
    },
    {
        name: 'AMD Radeon RX 7600 8GB',
        category: 'GPU',
        tags: ['8GB GDDR6', 'FSR'],
        price: 4_185_000,
        manufacturer: 'AMD',
    },
    {
        name: 'NVIDIA GeForce RTX 4070 12GB',
        category: 'GPU',
        tags: ['12GB GDDR6X', 'RTX'],
        price: 8_525_000,
        manufacturer: 'NVIDIA',
    },
    {
        name: 'AMD Radeon RX 7800 XT 16GB',
        category: 'GPU',
        tags: ['16GB GDDR6', 'FSR'],
        price: 7_750_000,
        manufacturer: 'AMD',
    },
    {
        name: 'NVIDIA GeForce RTX 5090 24GB',
        category: 'GPU',
        tags: ['24GB GDDR7', 'RTX'],
        price: 31_000_000,
        manufacturer: 'NVIDIA',
    },
    {
        name: 'AMD Radeon RX 7900 XTX 24GB',
        category: 'GPU',
        tags: ['24GB GDDR6', 'FSR'],
        price: 15_500_000,
        manufacturer: 'AMD',
    },
    {
        name: 'Corsair Vengeance LPX 16GB DDR4 3200MHz',
        category: 'RAM',
        tags: ['16GB', 'DDR4', '3200MHz'],
        price: 775_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'G.Skill Ripjaws V 16GB DDR4 3200MHz',
        category: 'RAM',
        tags: ['16GB', 'DDR4', '3200MHz'],
        price: 697_500,
        manufacturer: 'G.Skill',
    },
    {
        name: 'Corsair Vengeance 32GB DDR5 6000MHz',
        category: 'RAM',
        tags: ['32GB', 'DDR5', '6000MHz'],
        price: 1_860_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'G.Skill Trident Z5 32GB DDR5 6000MHz',
        category: 'RAM',
        tags: ['32GB', 'DDR5', '6000MHz'],
        price: 2_015_000,
        manufacturer: 'G.Skill',
    },
    {
        name: 'Corsair Dominator Platinum 64GB DDR5 7200MHz',
        category: 'RAM',
        tags: ['64GB', 'DDR5', '7200MHz'],
        price: 4_650_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'G.Skill Trident Z5 RGB 64GB DDR5 7200MHz',
        category: 'RAM',
        tags: ['64GB', 'DDR5', '7200MHz', 'RGB'],
        price: 4_960_000,
        manufacturer: 'G.Skill',
    },
    {
        name: 'WD Blue SN580 500GB NVMe',
        category: 'SSD',
        tags: ['500GB', 'NVMe', 'PCIe 4.0'],
        price: 620_000,
        manufacturer: 'WD',
    },
    {
        name: 'Samsung 980 500GB NVMe',
        category: 'SSD',
        tags: ['500GB', 'NVMe', 'PCIe 3.0'],
        price: 775_000,
        manufacturer: 'Samsung',
    },
    {
        name: 'Samsung 990 Pro 1TB NVMe',
        category: 'SSD',
        tags: ['1TB', 'NVMe', 'PCIe 4.0'],
        price: 1_550_000,
        manufacturer: 'Samsung',
    },
    {
        name: 'WD Black SN850X 1TB NVMe',
        category: 'SSD',
        tags: ['1TB', 'NVMe', 'PCIe 4.0'],
        price: 1_395_000,
        manufacturer: 'WD',
    },
    {
        name: 'Samsung 990 Pro 4TB NVMe',
        category: 'SSD',
        tags: ['4TB', 'NVMe', 'PCIe 4.0'],
        price: 4_650_000,
        manufacturer: 'Samsung',
    },
    {
        name: 'WD Black SN850X 4TB NVMe',
        category: 'SSD',
        tags: ['4TB', 'NVMe', 'PCIe 4.0'],
        price: 4_960_000,
        manufacturer: 'WD',
    },
    {
        name: 'Seagate BarraCuda 1TB 7200RPM',
        category: 'HDD',
        tags: ['1TB', '7200RPM'],
        price: 620_000,
        manufacturer: 'Seagate',
    },
    {
        name: 'WD Blue 1TB 7200RPM',
        category: 'HDD',
        tags: ['1TB', '7200RPM'],
        price: 697_500,
        manufacturer: 'WD',
    },
    {
        name: 'Seagate BarraCuda 4TB 7200RPM',
        category: 'HDD',
        tags: ['4TB', '7200RPM'],
        price: 1_240_000,
        manufacturer: 'Seagate',
    },
    {
        name: 'WD Blue 4TB 5400RPM',
        category: 'HDD',
        tags: ['4TB', '5400RPM'],
        price: 1_317_500,
        manufacturer: 'WD',
    },
    {
        name: 'Seagate IronWolf Pro 8TB NAS',
        category: 'HDD',
        tags: ['8TB', '7200RPM', 'NAS'],
        price: 3_100_000,
        manufacturer: 'Seagate',
    },
    {
        name: 'WD Red Pro 8TB NAS',
        category: 'HDD',
        tags: ['8TB', '7200RPM', 'NAS'],
        price: 3_410_000,
        manufacturer: 'WD',
    },
    {
        name: 'Dell S2421H 24 inch 1080p',
        category: 'Monitor',
        tags: ['24 inch', '1080p', '60Hz'],
        price: 1_550_000,
        manufacturer: 'Dell',
    },
    {
        name: 'ASUS VP249QGR 24 inch 1080p',
        category: 'Monitor',
        tags: ['24 inch', '1080p', '144Hz'],
        price: 2_015_000,
        manufacturer: 'ASUS',
    },
    {
        name: 'ASUS VG27AQ 27 inch 1440p',
        category: 'Monitor',
        tags: ['27 inch', '1440p', '170Hz'],
        price: 6_200_000,
        manufacturer: 'ASUS',
    },
    {
        name: 'LG 27GL83A-B 27 inch 1440p',
        category: 'Monitor',
        tags: ['27 inch', '1440p', '144Hz'],
        price: 3_875_000,
        manufacturer: 'LG',
    },
    {
        name: 'ASUS ROG Swift PG32UQX 32 inch 4K',
        category: 'Monitor',
        tags: ['32 inch', '4K', '144Hz', 'OLED'],
        price: 46_500_000,
        manufacturer: 'ASUS',
    },
    {
        name: 'Samsung Odyssey G9 49 inch 4K',
        category: 'Monitor',
        tags: ['49 inch', '4K', '240Hz', 'Curved'],
        price: 23_250_000,
        manufacturer: 'Samsung',
    },
    {
        name: 'Redragon K552 Kumara Red Switch',
        category: 'Keyboard',
        tags: ['Red Switch', 'RGB'],
        price: 500_000,
        manufacturer: 'Redragon',
    },
    {
        name: 'Logitech G213 Prodigy',
        category: 'Keyboard',
        tags: ['Membrane', 'RGB'],
        price: 800_000,
        manufacturer: 'Logitech',
    },
    {
        name: 'Corsair K70 RGB MK.2',
        category: 'Keyboard',
        tags: ['Cherry MX', 'RGB'],
        price: 1_500_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'Razer BlackWidow V3',
        category: 'Keyboard',
        tags: ['Green Switch', 'RGB'],
        price: 2_000_000,
        manufacturer: 'Razer',
    },
    {
        name: 'Razer Huntsman V2 Analog',
        category: 'Keyboard',
        tags: ['Optical Switch', 'RGB'],
        price: 4_000_000,
        manufacturer: 'Razer',
    },
    {
        name: 'Corsair K100 RGB',
        category: 'Keyboard',
        tags: ['Cherry MX Speed', 'RGB'],
        price: 3_500_000,
        manufacturer: 'Corsair',
    },
    {
        name: 'Logitech G102 Lightsync',
        category: 'Mouse',
        tags: ['8000 DPI', 'RGB'],
        price: 300_000,
        manufacturer: 'Logitech',
    },
    {
        name: 'Redragon M601 Centrophorus',
        category: 'Mouse',
        tags: ['3200 DPI'],
        price: 250_000,
        manufacturer: 'Redragon',
    },
    {
        name: 'Logitech G502 Hero',
        category: 'Mouse',
        tags: ['25600 DPI', 'RGB'],
        price: 800_000,
        manufacturer: 'Logitech',
    },
    {
        name: 'Razer DeathAdder V2',
        category: 'Mouse',
        tags: ['20000 DPI', 'RGB'],
        price: 1_000_000,
        manufacturer: 'Razer',
    },
    {
        name: 'Razer Viper V2 Pro',
        category: 'Mouse',
        tags: ['30000 DPI', 'Wireless'],
        price: 2_500_000,
        manufacturer: 'Razer',
    },
    {
        name: 'Logitech G Pro X Superlight',
        category: 'Mouse',
        tags: ['25600 DPI', 'Wireless'],
        price: 2_000_000,
        manufacturer: 'Logitech',
    },
    {
        name: 'HyperX Cloud Stinger 2',
        category: 'Headphones',
        tags: ['7.1 Surround', 'Wired'],
        price: 500_000,
        manufacturer: 'HyperX',
    },
    {
        name: 'Logitech G432',
        category: 'Headphones',
        tags: ['7.1 Surround', 'Wired'],
        price: 600_000,
        manufacturer: 'Logitech',
    },
    {
        name: 'SteelSeries Arctis 5',
        category: 'Headphones',
        tags: ['7.1 Surround', 'RGB'],
        price: 1_500_000,
        manufacturer: 'SteelSeries',
    },
    {
        name: 'Razer Kraken X',
        category: 'Headphones',
        tags: ['7.1 Surround', 'RGB'],
        price: 1_200_000,
        manufacturer: 'Razer',
    },
    {
        name: 'SteelSeries Arctis Nova Pro Wireless',
        category: 'Headphones',
        tags: ['Hi-Res Audio', 'Wireless', 'ANC'],
        price: 5_000_000,
        manufacturer: 'SteelSeries',
    },
    {
        name: 'Audeze Penrose',
        category: 'Headphones',
        tags: ['Planar Magnetic', 'Wireless'],
        price: 6_000_000,
        manufacturer: 'Audeze',
    },
];

export const categoryTags = products.reduce((set, p) => set.add(p.category), new Set()).size
    ? [...new Set(products.map((p) => p.category))].sort()
    : [];

    console.log(categoryTags);
    
